Repository DaPigGuy/PiggyFactions, pull requests merged in 2020-05, with the labels that each got.

#3 Add HRKChat tag usage examples w/ descriptions
  README.md
Labels: Type: Contribution

#34 Implement Faction logs
  README.md
  plugin.yml
  resources/english.yml
  resources/mysql.sql
  resources/sqlite.sql
  src/DaPigGuy/PiggyFactions/PiggyFactions.php
  src/DaPigGuy/PiggyFactions/commands/FactionCommand.php
  src/DaPigGuy/PiggyFactions/commands/subcommands/management/LogsSubCommand.php
  src/DaPigGuy/PiggyFactions/logs/FactionLog.php
  src/DaPigGuy/PiggyFactions/logs/LogsListener.php
  src/DaPigGuy/PiggyFactions/logs/LogsManager.php
Labels: Type: Enhancement

#50 Improved Localization
  resources/config.yml
  resources/languages/english.yml
  resources/mysql.sql
  resources/sqlite.sql
  src/DaPigGuy/PiggyFactions/EventListener.php
  src/DaPigGuy/PiggyFactions/PiggyFactions.php
  src/DaPigGuy/PiggyFactions/claims/ClaimsListener.php
  src/DaPigGuy/PiggyFactions/commands/FactionCommand.php
  src/DaPigGuy/PiggyFactions/commands/arguments/LanguageEnumArgument.php
  src/DaPigGuy/PiggyFactions/commands/subcommands/HelpSubCommand.php
  src/DaPigGuy/PiggyFactions/commands/subcommands/LanguageSubCommand.php
  src/DaPigGuy/PiggyFactions/commands/subcommands/TopSubCommand.php
  src/DaPigGuy/PiggyFactions/language/LanguageManager.php
  src/DaPigGuy/PiggyFactions/logs/LogsManager.php
  src/DaPigGuy/PiggyFactions/players/FactionsPlayer.php
  src/DaPigGuy/PiggyFactions/players/PlayerManager.php
  src/DaPigGuy/PiggyFactions/tasks/DisableFlightTask.php
Labels: Type: Enhancement

#51 Add German localization from Transifex
  resources/languages/german.yml
  src/DaPigGuy/PiggyFactions/language/LanguageManager.php
Labels: Type: Contribution, Type: Translation

#59 comply with ParoxityTeam/Commando v2.1.0
  .github/workflows/main.yml
  .poggit.yml
  src/DaPigGuy/PiggyFactions/commands/FactionCommand.php
  src/DaPigGuy/PiggyFactions/commands/subcommands/FactionSubCommand.php
Labels: Category: Virions
